name: Build and Deploy

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Jupyter and nbconvert
        run: |
          python -m pip install --upgrade pip
          pip install notebook nbconvert

      - name: Make script executable
        run: chmod +x .github/scripts/generate_markdown.sh

      - name: Run Markdown Generator
        run: .github/scripts/generate_markdown.sh Julia_Notebooks/
      
      - name: Copy Images from Notebooks to Markdown
        run: cp -r Julia_Notebooks/img Julia_Markdown/src/

      - name: Upload Generated Markdown
        uses: actions/upload-artifact@v4
        with:
          name: julia-markdown
          path: Julia_Markdown/

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.11.4'

      - name: Install Dependencies for Docs
        run: |
          julia --project=Julia_Markdown -e 'using Pkg; Pkg.instantiate(); Pkg.precompile()'

      - name: Generate Documentation and Upload 
        run: julia --project=Julia_Markdown Julia_Markdown/make.jl
